version: '3.7'

services:
  client:
    image: timbru31/node-alpine-git:14
    command: sh -c "yarn build && yarn serve"
    user: ${UID:-1000}:${GID:-1000}
    volumes: 
      - ./frontend:/frontend
    working_dir: /frontend
    environment:
      - HOME=/frontend
    ports:
      - 8080:8080
    network_mode: host
    labels:
      traefik.enable: 'true'
      traefik.http.routers.vue-playground.entrypoints: web
      traefik.http.routers.vue-playground.service: vue-playground
      traefik.http.routers.vue-playground.rule: 'Host(`vue.test`)'
      traefik.http.services.vue-playground.loadbalancer.server.port: '80'

  server:
    image: timbru31/node-alpine-git:14
    command: sh -c "yarn build && yarn serve"
    user: ${UID:-1000}:${GID:-1000}
    volumes: 
      - ./backend:/backend
    working_dir: /backend
    environment:
      - HOME=/backend
    ports:
      - "8080:8080"
